//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.WinForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoneclubeProducaoEntities : DbContext
    {
        public FoneclubeProducaoEntities()
            : base("name=FoneclubeProducaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBilhetacoesFebraban> tblBilhetacoesFebraban { get; set; }
        public virtual DbSet<tblCommissionOrders> tblCommissionOrders { get; set; }
        public virtual DbSet<tblCommissions> tblCommissions { get; set; }
        public virtual DbSet<tblContasFebraban> tblContasFebraban { get; set; }
        public virtual DbSet<tblDescontosFebraban> tblDescontosFebraban { get; set; }
        public virtual DbSet<tblEnderecosFebraban> tblEnderecosFebraban { get; set; }
        public virtual DbSet<tblHeadsFebraban> tblHeadsFebraban { get; set; }
        public virtual DbSet<tblLog> tblLog { get; set; }
        public virtual DbSet<tblLogTipo> tblLogTipo { get; set; }
        public virtual DbSet<tblOperadoras> tblOperadoras { get; set; }
        public virtual DbSet<tblPersons> tblPersons { get; set; }
        public virtual DbSet<tblPersonsAddresses> tblPersonsAddresses { get; set; }
        public virtual DbSet<tblPersonsImages> tblPersonsImages { get; set; }
        public virtual DbSet<tblPersonsPhones> tblPersonsPhones { get; set; }
        public virtual DbSet<tblPlanDetails> tblPlanDetails { get; set; }
        public virtual DbSet<tblPlanDetailType> tblPlanDetailType { get; set; }
        public virtual DbSet<tblPlans> tblPlans { get; set; }
        public virtual DbSet<tblPlansOptions> tblPlansOptions { get; set; }
        public virtual DbSet<tblReferred> tblReferred { get; set; }
        public virtual DbSet<tblResumosFebraban> tblResumosFebraban { get; set; }
        public virtual DbSet<tblServicosFebraban> tblServicosFebraban { get; set; }
        public virtual DbSet<tblTotalizadoresFebraban> tblTotalizadoresFebraban { get; set; }
    }
}
