//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPersons()
        {
            this.tblCommissionOrders = new HashSet<tblCommissionOrders>();
            this.tblPersonsPhones = new HashSet<tblPersonsPhones>();
            this.tblPersonsAddresses = new HashSet<tblPersonsAddresses>();
            this.tblPersonsImages = new HashSet<tblPersonsImages>();
            this.tblPlans = new HashSet<tblPlans>();
            this.tblReferred = new HashSet<tblReferred>();
            this.tblReferred1 = new HashSet<tblReferred>();
        }
    
        public int intIdPerson { get; set; }
        public System.DateTime dteRegister { get; set; }
        public string txtDocumentNumber { get; set; }
        public string txtName { get; set; }
        public string txtEmail { get; set; }
        public Nullable<System.DateTime> dteBorn { get; set; }
        public Nullable<int> intGender { get; set; }
        public Nullable<int> intIdPagarme { get; set; }
        public Nullable<int> intIdRole { get; set; }
        public Nullable<int> intContactId { get; set; }
        public string txtNickName { get; set; }
        public Nullable<long> matricula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCommissionOrders> tblCommissionOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonsPhones> tblPersonsPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonsAddresses> tblPersonsAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonsImages> tblPersonsImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPlans> tblPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReferred> tblReferred { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReferred> tblReferred1 { get; set; }
    }
}
