//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoneClube.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonsPhones
    {
        public int intId { get; set; }
        public Nullable<int> intIdPerson { get; set; }
        public Nullable<int> intDDD { get; set; }
        public Nullable<long> intPhone { get; set; }
        public Nullable<bool> bitPhoneClube { get; set; }
        public Nullable<int> intIdOperator { get; set; }
    
        public virtual tblPersons tblPersons { get; set; }
    }
}
